/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ifba.curso.view;

/**
 *
 * @author gugsa
 */
public class CursoListar extends javax.swing.JFrame {

    /**
     * Creates new form CursoListar
     */
    public CursoListar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProcurar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProcurar.setBackground(new java.awt.Color(255, 255, 255));
        txtProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(txtProcurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Código do Curso"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 490, 340));

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 90, -1));

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 50, 90, -1));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 90, -1));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcurarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcurarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Pega a linha selecionada na tabela
    int linhaSelecionada = jTable1.getSelectedRow();

    if (linhaSelecionada == -1) {
        // Nenhuma linha selecionada
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Selecione um curso para excluir!", 
            "Aviso", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Pega o nome do curso da linha selecionada (coluna 0)
    String nomeCurso = jTable1.getValueAt(linhaSelecionada, 0).toString();

    // Mostra a mensagem de confirmação
    int confirmacao = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Tem certeza que deseja excluir: " + nomeCurso + "?",
        "Confirmação",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    // Se o usuário clicou em "Sim"
    if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
        // Aqui você remove da tabela (e futuramente do arquivo)
        javax.swing.table.DefaultTableModel model = 
            (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.removeRow(linhaSelecionada);

        javax.swing.JOptionPane.showMessageDialog(this, 
            "Curso \"" + nomeCurso + "\" excluído com sucesso!");
    }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // cria uma nova janela (JFrame)
    javax.swing.JFrame frame = new javax.swing.JFrame("Editar Curso");

    // adiciona o painel CursoAdicionar dentro dessa janela
    frame.setContentPane(new CursoEditar());
    
    // ajusta o tamanho conforme o conteúdo
    frame.pack();
    
    // centraliza a janela na tela
    frame.setLocationRelativeTo(null);
    
    // mostra a janela
    frame.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // cria uma nova janela (JFrame)
    javax.swing.JFrame frame = new javax.swing.JFrame("Adicionar Curso");

    // adiciona o painel CursoAdicionar dentro dessa janela
    frame.setContentPane(new CursoAdicionar());
    
    // ajusta o tamanho conforme o conteúdo
    frame.pack();
    
    // centraliza a janela na tela
    frame.setLocationRelativeTo(null);
    
    // mostra a janela
    frame.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtProcurar;
    // End of variables declaration//GEN-END:variables

   }
